### ISSUE TITLE
Refactor tactics into a separate file?

### ISSUE THREAD

**Issue by xuanruiqi** [affeldt-aist/succinct#1]
Should we refactor custom tactics into a separate file to have more modularity? @garrigue what do you think?

**Comment by garrigue** [comment]
I'm not sure.
It might make sense for decompose_rewrite, which is generic enough, but the tactics at the end of dynamic_redblack are very specific, and are just there to factorize the proof, which is not very convincing yet.
Actually the first goal was to make the checking faster, and this succeeded to some extent.

**Comment by xuanruiqi** [comment]
If it's just one tactic, it might be better to leave it as is. If we do write some more tactics in the future, maybe we can refactor those into a tactics library.
