### ISSUE TITLE
jacobson_rank_complexity.v does not type check in newer versions of Coq

### ISSUE THREAD

**Issue by xuanruiqi** [affeldt-aist/succinct#4]
I just upgraded my Coq to 8.9.0 and figured that jacobson_rank_complexity.v does not type check anymore. The following error message was displayed:

    Error:
    In environment
    sz : nat
    s : seq bool
    number_of_blocks := size s %/ sz : nat
    x : nat
    s' : seq bool
    Unable to unify "succn (Z.abs_nat (floor (log (size s'))))" with
    "succn (Z.abs_nat (floor (log (size s))))".

**Comment by garrigue** [comment]
Fails in dynamic_redblack.v too.

**Comment by xuanruiqi** [comment]
@garrigue I can fix that one.

**Comment by affeldt-aist** [comment]
The failure in jacobson_rank_complexity is old code coming from ca. 2016.
